rootProject.name = "Weather App"
include(":app")
include(":common")
include(":network")
include(":dtos")
include(":business")
include(":cities")
include(":citiesRepository")
include(":LocalPersistance")
include(":weather")
include(":weatherRepository")
